### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by hzhou81** [GavWood/Game-Framework#1]
In GameViewController.mm , is your arsession.run() successfully return available while AVCaptureSession is working?

**Comment by GavWood** [comment]
I’m working on this now with ios11 so there will be an update soonish. Currently trying to get the video to sit behind the open gles context and then I’ll post some updates!

**Comment by GavWood** [comment]
Good question - it didn't. In doing the calculations in ARKit with YUV the callback of the RGB capture feed is disabled.

I've added code to didUpdateFrame to process the image.
