### ISSUE TITLE
Sorry, unable to build

### ISSUE THREAD

**Issue by kalloc** [GavWood/Game-Framework#3]
Hi, I had time to play with app.
But unfortunately, xcode didn't build.
It wrote that not found MurmurationOSX_Prefix.pch, game.OSXz and utility.OSXz.

Can I ask you, is your project buildable or not?

**Comment by GavWood** [comment]
Hi Kalloc,

Yes it's buildable. The game.OSz and utility.OSXz files are binaries and as
suck - you shouldn't really check them in to GitHub.
You use the packer I put there.

As for the pch. There is an xcode option to remove it. I'll do that and
check it in for you.

I've had a researcher from Netherlands build it - and he's experimenting
with it no problem - so I promise you it works.

>
Gavin

**Comment by GavWood** [comment]
suck, i mean as such.

**Comment by kalloc** [comment]
![image](https://user-images.githubusercontent.com/177687/35477903-9e07aac4-03df-11e8-9d4f-b69eb37a03c9.png)

**Comment by GavWood** [comment]
Hi,

I've added the binaries here:
https://www.dropbox.com/sh/0kjkyv9cjmxd1me/AABQFEpYnaowa3kMvPJaakBpa?dl=0

Normally you need to build these using the packer. This does speed up load times (particularly relevant if you are changing code for the murmurations).

Answer to pch problem - now checked in:
https://github.com/GavWood/DOGE-Game-Engine/wiki/Problems-with-.pch-file

More on building binaries:
https://github.com/GavWood/DOGE-Game-Engine/wiki/Missing-game-binary-(.OSXz)
